services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    networks:
      - laravel
    depends_on:
      - db
    ports:
      - "8000:80"

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: larwaapi
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: larwaapi
      MYSQL_PASSWORD: secret
    networks:
      - laravel
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - laravel

volumes:
  dbdata:

networks:
  laravel:
    driver: bridge
